PREP(applyGodMode);
PREP(applyInfiniteAmmo);
PREP(blockAceMedicalDamage);
PREP(handleDamage);
PREP(handleFiredMan);
PREP(registerPlayerHandlers);
PREP(refillWeaponMagazine);
PREP(toggleGodMode);
PREP(toggleInfiniteAmmo);
